cypress-io/circleci-orb

README.md
docs/examples.md
docs/jobs.md
package.json
src/orb.yml

feat: add "wait-on" job parameter to delay tests until URL responds

---

docs/examples.md
scripts/utils.ts
src/orb.yml
test/examples.test.ts

- close #56 
this allows to use this orb with Mac / Linux parallel builds

feat: cache dependencies per architecture, close #56

---

src/orb.yml

additional boolean paramter to use yarninstead of npm ci.
that condition is used for install and cache steps through all jobs and
commands.
This is offered as potential solution to #65 an #28

Add support for yarn

---

README.md
docs/examples.md
package-lock.json
package.json
src/orb.yml

Add npm auth example

---

README.md
docs/examples.md
scripts/examples.ts

Spelling fix

---

docs/examples.md
docs/jobs.md
scripts/examples.ts
src/orb.yml

feat: add no-workspace parameter, close #4

---

docs/examples.md
docs/jobs.md
src/orb.yml

To make it clearer what is going on in each parameter and example

Add more parameter and example explanations

---

src/orb.yml

I added names to the verify and build steps. This is untested, please let me know if I should test these changes.

Add missing names to steps

---

docs/examples.md
docs/jobs.md
src/orb.yml

fix: Add `cache-key` parameter to the `install` Job

---

README.md

- Added missing period at end of sentences.
- Added missing colon at end of sentences.

updated missing punctuation in the README.md file

---

CONTRIBUTING.md

Improve clarity in documentation.

Fix typo on CONTRIBUTING.md

---

README.md
docs/executors.md
src/orb.yml

feat: switch to Node 12.14.0 base image

---

README.md
docs/examples.md
docs/jobs.md
scripts/examples.ts
src/orb.yml

- closes #224
```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@1
workflows:
build:
jobs:
- cypress/run:
config-file: staging.json
```

feat: add config-file parameter

---

README.md
docs/examples.md
docs/jobs.md
scripts/examples.ts
src/orb.yml

feat: add tags support

---

.circleci/config.yml
docs/examples.md
docs/jobs.md
package-lock.json
package.json
scripts/examples.ts
src/orb.yml

- fix orb home url to be an url
- added new parameter to `cypress/run` job to attach workspace, this is similar to `parallel: true` but more obvious
```yml
workflows:
build:
jobs:
- cypress/install
- cypress/run:
requires:
- cypress/install
attach-workspace: true
```

feat: add attach-workspace option

---

docs/examples.md
docs/jobs.md
scripts/examples.ts
src/orb.yml

- closes #236 
```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@1
workflows:
build:
jobs:
- cypress/run:
install-command: 'yarn install --frozen-lockfile --production=true'
```

feat: add custom install command

---

docs/examples.md
docs/jobs.md
scripts/examples.ts
src/orb.yml

- closes #232
```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@1
workflows:
build:
jobs:
- cypress/run:
post-checkout:
- run: echo Scaffolding before installing
```

feat: add post-checkout

---

src/orb.yml

- close #242 
- tested in https://circleci.com/gh/cypress-io/workflows/cypress-example-circleci-orb/tree/test-yarn
- combined all install commands conditions into single bash block

fix: combine install commands into a single script

---

README.md
docs/recipes.md

add Postgres database + Hasura engine multiple services recipe

---

README.md

explain Orb name

---

README.md
docs/examples.md
scripts/examples.ts
src/orb.yml

- closes #261
Adds an example, since we did not have it and the docs at https://circleci.com/docs/2.0/configuration-reference/#filters are not very helpful

Branch example

---

.prettierrc.json
.vscode/settings.json
manual-tests/build-step.test.ts
manual-tests/config.test.ts
manual-tests/install-job.test.ts
manual-tests/run-parameters.test.ts
manual-tests/store-artifacts.test.ts
package-lock.json
package.json
scripts/examples.ts
scripts/executors.ts
scripts/jobs.ts
scripts/publish.js
scripts/utils.ts
test/examples.test.ts
test/simple.test.ts

- closes #285 
- added script to format
- added VSCode settings
- added pre-commit hook

Set up prettier

---

README.md
docs/recipes.md

Recently needed to add nightly workflow and could not find a recipe to copy

Add recipe with nightly workflow

---

README.md
package-lock.json
package.json

updated the readme orb examples to use v2 of the circle orb.

Orb v2 release for Cypress v10

---

docs/executors.md
src/orb.yml

Added 3 new executors.
** Note: ** this will also incorporate #370

minor: add new executors for Node 16 and updated browsers.

---

package.json

I forgot to increment the version in `package.json`

fix: update version number

---

package-lock.json
package.json

- Update `ts-node` to `10.9.1`.
- Update `@types/node` to `16.11.57`.
Fixes #335

fix: update tsnode and node types

---

.github/workflows/snyk_sca_scan.yaml
.github/workflows/snyk_static_analysis_scan.yaml

This PR adds security controls in support of vulnerability scanning for third party packages as well as first party code. 
Snyk is already implemented, but these actions bring the Cypress Tools into alignment with our vulnerability management strategy. The actions that this pull request introduces send the scan results back to the Snyk dashboard. The Snyk dashboard is then coupled with branch protection rules that dictate our levels of protection by blocking PRs where this git action fails as a check.
Once the solution is fully implemented, the failures you see on the PR related to this would prevent merges of the code to the 'develop' and 'master' branches. The exit status it failed with today indicates that there is a critical vulnerability in the code base. This PR aims to increase …

SEC-229 | Initial Commit of Snyk Git Actions

---

.circleci/test-deploy.yml
examples/angular-app/package-lock.json
examples/angular-app/package.json
examples/custom-install/package-lock.json
examples/custom-install/package.json
examples/npm-install/package-lock.json
examples/npm-install/package.json
examples/yarn-install/package.json
examples/yarn-install/yarn.lock
src/commands/install.yml
src/examples/browser.yml
src/examples/edge.yml
src/executors/default.yml
src/jobs/run.yml

This PR uses the [CircleCI Browser Tools Orb](https://circleci.com/developer/orbs/orb/circleci/browser-tools) to define our executors we will run Cypress with:

Support executors

---

README.md

Just some content tweaks to help both highlight concepts and give a hierarchy for improved readability.

Readme - content updates

---

README.md

Minor copy updates to tighten things up a bit.

Copy updates

---

README.md

This PR updates the documentation to align with the v3 orb changes.

docs: update README for new orb

---

ISSUE_TEMPLATE.md
LICENSE.md
README.md

- Restored some additional info that got removed in the v3 push. These could still be useful.
- Restored the issue template and license docs
- Small copy clean up

V3 docs edits

---

src/examples/edge.yml

Update edge example

---

examples/angular-app/angular.json
examples/angular-app/package-lock.json
examples/angular-app/package.json
examples/angular-app/src/app/app.component.html

- supports the resolution of issue https://github.com/cypress-io/circleci-orb/issues/481
The Angular project in [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) is currently configured to use Angular `16.2.12`. This version has already transitioned out of active support and its LTS support ends in Nov 2024 (see [Actively supported versions](https://angular.dev/reference/releases#actively-supported-versions)).
Additionally, as listed in [Angular - Version compatibility](https://angular.dev/reference/versions), Angular `16.x` is constrained to `^16.14.0 || ^18.10.0` which causes Node.js version inconsistencies in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml), where …

test(deps): update angular example to version 17.3.12

---

.circleci/test-deploy.yml
src/examples/node-version.yml
src/executors/default.yml
src/jobs/run.yml

feat: Allow choosing a Node version in the run job

---

src/examples/node-version.yml

docs: examples/node-version

---

.circleci/test-deploy.yml
examples/pnpm-install/cypress.config.js
examples/pnpm-install/cypress/e2e/spec.cy.js
examples/pnpm-install/package.json
examples/pnpm-install/pnpm-lock.yaml
src/@orb.yml

bumping node orb to enable pnpm

---

.circleci/test-deploy.yml
examples/angular-app/package-lock.json
examples/angular-app/package.json
examples/custom-install/package-lock.json
examples/custom-install/package.json
examples/npm-install/package-lock.json
examples/npm-install/package.json
examples/pnpm-install/package.json
examples/pnpm-install/pnpm-lock.yaml
examples/wait-on/package-lock.json
examples/wait-on/package.json
examples/yarn-install/package.json
examples/yarn-install/yarn.lock
src/@orb.yml

Fix https://github.com/cypress-io/circleci-orb/issues/504

fix: update browser-tools to 1.5.1

---

.circleci/config.yml
.circleci/test-deploy.yml
.circleci/test_deploy.yml
CONTRIBUTING.md

Closes https://github.com/cypress-io/circleci-orb/issues/501

chore: bumb orb tools

---

src/examples/browser.yml
src/examples/caching.yml
src/examples/component.yml
src/examples/custom-install.yml
src/examples/edge.yml
src/examples/node-version.yml
src/examples/pnpm.yml
src/examples/recording.yml
src/examples/run.yml
src/examples/yarn.yml

Parameter descriptions as shown on https://circleci.com/developer/orbs/orb/cypress-io/cypress have grammatical errors / typos and inconsistencies in them.
Rework the parameter descriptions to remove grammatical errors / typos.

docs: revise parameter descriptions
