cypress-io/circleci-orb

docs/jobs.md, src/orb.yml
- closes #50 and avoids problems for people without parallelization feature in the plan
=> fix: do not set default group name, close #50

docs/examples.md, src/orb.yml
Resolves #72 by passing the `--frozen-lockfile` flag when running `yarn install` in the `setup` command and updating the relevant docs.
=> Add --frozen-lockfile flag to 'yarn install'

src/orb.yml
Adds a `working_directory` parameter to most commands and jobs.
Fixes https://github.com/cypress-io/circleci-orb/issues/113 and https://github.com/cypress-io/circleci-orb/issues/16.
=> Add working directory parameter

README.md
`build processing` is `pipelines` now.
Ref: https://github.com/circleci/circleci-docs/pull/3281
=> Fix how to enable Orbs

docs/executors.md, src/orb.yml, test/simple.test.ts
I added Chrome 73 to 76 to the executors with the existing docker images (https://hub.docker.com/r/cypress/browsers/tags).
I have included a new test in simple.test.ts to ensure the executors can be used with cypress/run and cypress/install.
Note:
I have not published this change as a dev version to the CircleCI orb repo yet. Are the Cypress developer welcoming other people to publish CircleCI orbs?
=> Add chrome 73-76 to the executors

src/orb.yml
=> Add support for 'no_output_timeout' CircleCI key when running tests

docs/examples.md, docs/jobs.md, package-lock.json, package.json, scripts/examples.ts, src/orb.yml
For example, this will allow us to install Cypress pre-release and cache it.
```yaml
- cypress/run:
post-install:
- run:
name: Install Cypress pre-release
environment:
CYPRESS_INSTALL_BINARY: https://cdn.cypress.io/beta/binary/3.6.1/linux-x64/circle-issue-1096-firefox-support-42fcf58b442cc6bdbc35f3d5e2c34682f910badc-184089/cypress.zip
command: npm install https://cdn.cypress.io/beta/npm/3.6.1/circle-issue-1096-firefox-support-42fcf58b442cc6bdbc35f3d5e2c34682f910badc-184085/cypress.tgz
executor: cypress/browsers-chrome73-ff68
```
=> Add post install step

docs/executors.md, src/orb.yml
Please have Chrome 77 and Chrome 78 available in the executors.
A typo has been fixed for Chrome 76 executor documentation.
Let me leave the Cypress maintainers to publish a new version of the orb. :)
P.S. In the future, should we remove some very old versions of Chrome in the future orb releases?  I haven't found any way to do a "include" in the orb.yml file.  If we keep adding executors, the file is getting hairy.
=> feat: Include Chrome 77-78 in the executors

src/orb.yml
Both Linux and macOS executers will write to the same cache dir (`~/.cache/Cypress`) which will persist between jobs of the same workflow.
Fixes #98
=> fix: set explicit cache folder

src/orb.yml
Display a link to your home page and the orb source natively in the Orb registry as a clickable link.
=> Add Home URL and Source Code URL

src/orb.yml
As I mentioned in #238 it's not a good idea to do `--production=true` because most people put Cypress in `devDeps`
=> Remove prod=true yarn call to avoid confusion

README.md, docs/examples.md, docs/jobs.md, scripts/examples.ts, src/orb.yml
- closes #295
```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@1
workflows:
build:
jobs:
- cypress/install
- cypress/run:
requires:
- cypress/install
record: true
parallel: true
parallelism: 2
ci-build-id: testing-commit-$CIRCLE_SHA1
```
=> feat: add ci-build-id run job parameter

CONTRIBUTING.md, manual-tests/install-job.test.ts, scripts/utils.ts, src/orb.yml
- closes #315 
- passes `working_directory` and applies to the `build` step
Note: before the build command was declared as "steps" internally, but seems we can just use a string, since we never passed multiple commands.
=> feat: pass the working directory with build command to the install job

.circleci/config.yml
Updates `config.yml` to use `cimg/node:16.14.2` which is a CircleCI best practice and the same Node version we currently test against in our cypress-docker-images repo. 
Fixes #365
=> fix: update image per circleci best practices.

src/orb.yml
My cypress/run CI job is currently failing due to
> Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository
because the following steps are always applied:
```
- attach_workspace:
at: ~/
- checkout
```
`checkout` should only be present when you're not attaching a workspace, but currently, `attach-workspace: false` doesn't stop workspaces being attached due to the broken conditional, hence the job failing if the workspace has anything inside it.
Fixes https://github.com/cypress-io/circleci-orb/issues/293
=> fix: only attach workspace when required

src/executors/default.yml
This is a small PR that assigns the default executor to the cypress base docker image of 16.16
=> feat: add default cypress base image

.circleci/test-deploy.yml, src/@orb.yml, src/jobs/run.yml
This adds support to lean into the `circleci/orb-tools@5` to handle dependency installation
=> feat: use node orb

CONTRIBUTING.md
This PR updates the `CONTRIBUTING` guide with the necessary steps for publishing
=> docs: update CONTRIBUTING guide to include publishing steps

src/commands/run-tests.yml
Closes #418 
The orb should automatically save video and screenshot artifacts to CircleCi. When users are not specifying a `working-directory` parameter, the default of `""` causes the artifact storage page to be an absolute path instead of a relative path, leading to missing artifacts in CircleCI.
=> fix: correct cypress/run tests default value for working-directory param

src/@orb.yml
- Closes https://github.com/cypress-io/circleci-orb/issues/434
chore: update circleci/browser-tools to latest version which fixes problem installing chromedriver.  [CircleCi](https://github.com/CircleCI-Public/browser-tools-orb/issues/75#issuecomment-1641137783) fixed a problem where the endpoint CircleCi uses for downloading chrome driver changed for all versions >= 115.
=> chore: update circleci/browser-tools to latest version 

.circleci/test-deploy.yml, src/examples/node-version.yml, src/executors/default.yml
This PR updates the default node version to `18.16` and adds documentation for how to change the default node version in the `cypress/default` executor.
=> feat: Update node defaults

examples/angular-app/package-lock.json, examples/angular-app/package.json, examples/custom-install/package-lock.json, examples/custom-install/package.json, examples/npm-install/package-lock.json, examples/npm-install/package.json, examples/wait-on/package-lock.json, examples/wait-on/package.json, examples/yarn-install/package.json, examples/yarn-install/yarn.lock
This PR updates the `cypress` version used for our test-deploys that is failing because of a Chrome bug https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1904/workflows/541a733f-0ac0-4917-a892-4b4c8fd7d00d/jobs/6180
=> chore: update cypress version

src/@orb.yml
Pin the version @1 so that non-breaking updates and fixes can be pulled in automatically as they arise.
=> chore: set circleci browser tools orb to pull v1 with updates

src/@orb.yml
Close https://github.com/cypress-io/circleci-orb/issues/460
A downstream fix was published in browser-tools-orb: https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.8 to address an issue where downloading the chrome browser results in a 404 and does not install.
Since orbs are immutable as noted in [this thread](https://github.com/cypress-io/circleci-orb/issues/460#issuecomment-1974810503), we need to explicitly set a version for our dependency orb and republish to get this fix.
=> fix: bump browser tools to fix 404 on chrome install

examples/angular-app/package-lock.json, examples/angular-app/package.json, examples/custom-install/package-lock.json, examples/custom-install/package.json, examples/npm-install/package-lock.json, examples/npm-install/package.json, examples/wait-on/package-lock.json, examples/wait-on/package.json, examples/yarn-install/package.json, examples/yarn-install/yarn.lock
- closes https://github.com/cypress-io/circleci-orb/issues/471
The [examples](https://github.com/cypress-io/circleci-orb/tree/master/examples) directory contains example sub-directories using [cypress@13.2.0](https://docs.cypress.io/guides/references/changelog#13-2-0) released on Sep 12, 2023.
- For Firefox `124.0` and later, a minimum of [cypress@13.7.1](https://docs.cypress.io/guides/references/changelog#13-7-1) is needed.
- Issue https://github.com/cypress-io/circleci-orb/issues/471 needs a minimum of [cypress@13.9.0](https://docs.cypress.io/guides/references/changelog#13-9-0) to resolve.
Update all [examples](https://github.com/cypress-io/circleci-orb/tree/master/examples) directories to use [cypress@13.13.0](https://docs.cypress.io/guides/references/changelog#13-13-0), released July …
=> test(deps): update cypress examples to 13.13.0

.circleci/test-deploy.yml
- Closes https://github.com/cypress-io/circleci-orb/issues/476
The CI workflow [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) shows in the logs https://app.circleci.com/pipelines/gh/cypress-io/circleci-orb/1945
```text
Error calling workflow: 'test-deploy'
Error calling job: 'orb-tools/publish'
Missing required argument(s): orb_name, vcs_type
```
- PR #469 has attempted an incomplete update to CircleCI `orb-tools` v12 without paying regard to the [Migration Guide](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/MIGRATION.md)
=> Revert "chore(deps): update dependency orb-tools to v12 (#469)"

.circleci/test-deploy.yml
- closes https://github.com/cypress-io/circleci-orb/issues/448
The CircleCI workflow [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) is configured to use the Docker container:
`cypress/browsers:node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1`
for component testing of [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app).
Node.js `16` already reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 11, 2023 and is no longer supported.
- ~~[examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) is currently configured for Angular `15.1`~~
- …
=> ci(deps): update ct docker image to cypress/browsers:node-18.20.3

.circleci/test-deploy.yml
- closes https://github.com/cypress-io/circleci-orb/issues/481
The workflow [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) is using mixed major versions of Node.js `18.x` and `20.x` (`18.20.3` & `20.6.0`).
https://github.com/cypress-io/circleci-orb/blob/cc4944de6aaa74cf9cdbbad422e1e8a2061218a8/.circleci/test-deploy.yml#L10-L13
https://github.com/cypress-io/circleci-orb/blob/cc4944de6aaa74cf9cdbbad422e1e8a2061218a8/.circleci/test-deploy.yml#L25-L26
- [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) is currently configured for Angular `17.3.2`
- [Angular - Version compatibility](https://angular.dev/reference/versions) shows Angular `17.3` compatible with Node.js 	`^18.13.0 || …
=> ci(deps): update test-deploy to node 20.15.1 LTS

src/examples/edge.yml
- Closes https://github.com/cypress-io/circleci-orb/issues/488
The Edge example in [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) fails with the message:
> Can't run because you've entered an invalid browser name.
>
> Browser: edge was not found on your system or is not supported by Cypress.
Replace the `usage` section in [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) with the following workflow code:
```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@3
executors:
cypress-browsers:
docker:
- image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
jobs:
edge-test:
executor: cypress-browsers
steps:
- cypress/install
- cypress/run-tests: …
```
=> docs: replace and fix edge example

src/commands/install.yml
Currently the **pnpm example** test is failing. This seems to be due to an old version of `pnpm` being present on the machine ([version 8 instead of version 9](https://app.circleci.com/pipelines/github/ramykl/circleci-orb/20/workflows/fd6a1923-37af-4016-807f-25ac2cf44fb6/jobs/81?invite=true#step-106-46_5)). I'm still a little unsure why this is the case...I would either expect pnpm not to be installed at all or for it to install the latest version as pnpm isn't packaged with node...maybe a cache hit?
After doing various testing https://github.com/ramykl/circleci-orb/pull/4 (sorry for the bad commit messages) it seems like the node orb doesn't install the package manager when using `node/install-packages`.
This will explicitly install the pnpm package manager through the node orb, which by …
=> fix: Fix the PNPM example test

.circleci/test-deploy.yml
- relates to issue https://github.com/cypress-io/circleci-orb/issues/493
The `test-deploy` workflow in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) fails running the job `name: Pnpm Example`, in the step "Installing PNPM packages", when triggered by tag creation, with the error message:
```text
 WARN  Ignoring not compatible lockfile at /home/circleci/project/examples/pnpm-install/pnpm-lock.yaml
node_modules/.pnpm                       |  WARN  Ignoring not compatible lockfile at /home/circleci/project/examples/pnpm-install/node_modules/.pnpm/lock.yaml
 ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is present
Note that in CI environments this setting is true by default. If you still need …
```
=> fix: CI Pnpm example lockfile incompatibility

CONTRIBUTING.md
The instructions in the [CONTRIBUTING](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#local-packing) document to execute a job locally do not work. For instance, in the section [CircleCI Local Review](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#circleci-local-review) the following command:
```shell
circleci local execute --job orb-tools/review
```
results in the error message:
> Error: unknown flag: --job
The help text is also shown:
```text
┃  circleci local execute                                                                                                ┃
┃                                                                                                                        ┃
┃  Usage: …
```
=> docs: fix local execute instructions

CONTRIBUTING.md
The instructions in [CONTRIBUTING > Local Packing](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#local-packing) do not result in the generation of a file `orb.yml` which is needed for the command `circleci orb validate orb.yml`.
The CircleCI documentation [Orb packing](https://circleci.com/docs/orb-concepts/#orb-packing) quotes the example command that generates a file:
```shell
circleci orb pack <dir> > orb.yml
```
Correct the instructions in [CONTRIBUTING > Local Packing](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#local-packing) to read:
```shell
circleci orb pack ./src > orb.yml
```
=> docs: fix orb pack instructions

.gitignore, CONTRIBUTING.md
Fix typos in the [CONTRIBUTING.md](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md) document, and one in [.gitignore](https://github.com/cypress-io/circleci-orb/blob/master/.gitignore)
=> docs: fix CONTRIBUTING typos

.circleci/test-deploy.yml
The workflow [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) uses the Cypress Docker image:
`cypress/browsers:node-20.15.1-chrome-126.0.6478.126-1-ff-128.0-edge-126.0.2592.102-1`
According to https://docs.cypress.io/app/references/launching-browsers#Browser-versions-supported only the latest 3 major versions of browsers are supported.
| Browser | Current version | Lowest supported |
| ------- | --------------- | ---------------- |
| Chrome  | 133.x           | >= 131.x         |
| Firefox | 135.x           | >= 133.x         |
| Edge    | 133.x           | >= 131.x         |
Update [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) to use
`cypress/browsers:22.14.0` …
=> test(deps): update to cypress/browsers:22.14.0 and node 22.14.0

.circleci/test-deploy.yml, examples/pnpm-install/package.json, examples/pnpm-install/pnpm-lock.yaml
- closes https://github.com/cypress-io/circleci-orb/issues/509
The pnpm example is disabled in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) because it failed to run.
- Update Cypress in [examples/pnpm-install](https://github.com/cypress-io/circleci-orb/tree/master/examples/pnpm-install) to Cypress `14.x` with `pnpm@10.4.1` installed using `"cypress": "^14.0.0"` and `pnpm:onlyBuiltDependencies` to allow the Cypress binary to run.
- Remove `dlx` from the command `pnpm dlx cypress install` in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml)
=> test: update and re-enable pnpm example

src/examples/edge.yml
The Edge browser version in the Cypress Docker image used in the [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml)
`cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1`
is no longer [supported by Cypress](https://docs.cypress.io/app/references/launching-browsers#Browser-versions-supported).
The current major version of the Microsoft Edge browser in the [stable release channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel) is `135`. Cypress therefore currently supports versions `133`, `134` and `135`, which excludes version `129`.
Update the [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) to use the Cypress Docker …
=> docs: update Edge example to cypress/browsers:22.15.0

src/@orb.yml, src/executors/default.yml, src/jobs/run.yml
BREAKING CHANGE:
- closes https://github.com/cypress-io/circleci-orb/issues/518
Orb defaults to Node.js `18.16.1`
https://github.com/cypress-io/circleci-orb/blob/0292fa38d0a16ba15d982a870be31af43e6825af/src/executors/default.yml#L6
Node.js 18.x reaches [End-of-Life](https://github.com/nodejs/release#release-schedule) in a few days on Apr 30, 2025.
- Update the default Node.js from `18.16.1` to `22.15.0` from the [Active LTS Node.js](https://github.com/nodejs/release#release-schedule) release line.
- Update CircleCI Orb usage
- [circleci/node](https://circleci.com/developer/orbs/orb/circleci/node) from 6 to 7
- [circleci/browser-tools](https://circleci.com/developer/orbs/orb/circleci/browser-tools) from `1.5.1` to `1.5.3`
=> feat: update default node.js to 22.15.0

README.md, src/examples/browser.yml, src/examples/caching.yml, src/examples/commands.yml, src/examples/component.yml, src/examples/custom-install.yml, src/examples/edge.yml, src/examples/mono-repo.yml, src/examples/node-version.yml, src/examples/pnpm.yml, src/examples/recording.yml, src/examples/run.yml, src/examples/wait-on.yml, src/examples/yarn.yml
- The [README](https://github.com/cypress-io/circleci-orb/blob/master/README.md) document shows the use of `cypress-io/cypress@3` although https://circleci.com/developer/orbs/orb/cypress-io/cypress is showing `cypress-io/cypress@4.0.0`
- Examples on https://circleci.com/developer/orbs/orb/cypress-io/cypress such as https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-browser still show `cypress-io/cypress@3`
- Update the text of the [README](https://github.com/cypress-io/circleci-orb/blob/master/README.md) to refer to `cypress-io/cypress@4`
- Update examples in [src/examples](https://github.com/cypress-io/circleci-orb/tree/master/src/examples) to use `cypress-io/cypress@4`
=> fix: update documentation and examples to orb v4

.circleci/test-deploy.yml, src/jobs/run.yml
- Add the option to pass through `resource_class` to the `run` job.
- Limit possible `resource_class` values to valid Docker resource classes
Closes #503
=> feat: Enable configuring Docker `resource_class` for `run` job

.circleci/test-deploy.yml, src/commands/install.yml, src/examples/browser.yml, src/examples/edge.yml, src/jobs/run.yml
- resolves https://github.com/cypress-io/circleci-orb/issues/528
- closes https://github.com/cypress-io/circleci-orb/pull/530 by replacing it
- Issue https://github.com/cypress-io/circleci-orb/issues/528 proposes to support Chrome for Testing and Edge browsers through `v2` of the CircleCI Orb [circleci/browser-tools](https://circleci.com/developer/orbs/orb/circleci/browser-tools)
- PR https://github.com/cypress-io/circleci-orb/pull/530 has attempted to implement this proposal, however there are multiple failures in the PR
- In [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml)
- Change Edge tests in the job `run-ct-tests-in-edge` to run in the orb's `cypress/default` executor (instead of running in `cypress/browsers:22.16.0`)
- …
=> feat: use CircleCI Chrome for Testing and Edge

.circleci/test-deploy.yml
The newly-added job `run-ct-tests-in-chrome-for-testing` in the pipeline configuration [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) records into the Cypress Cloud group `2x-edge`. This is in conflict with the job `run-ct-tests-in-edge` which uses the same group and a different browser, leading to recording failures, that in turn cause the job to fail.
Record from the job `run-ct-tests-in-chrome-for-testing` in the pipeline configuration [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) into the Cypress Cloud group `2x-chrome-for-testing`.
=> test: correct chrome for testing record group

.circleci/test-deploy.yml
- closes https://github.com/cypress-io/circleci-orb/issues/544
CI tests in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) include Component Testing of the [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) in different browsers, using two different executors:
| job                                  | executor                   | type         |
| ------------------------------------ | -------------------------- | ------------ |
| `run-ct-tests-in-chrome`             | `cypress/browsers:22.17.0` | docker image |
| `run-ct-tests-in-chrome-for-testing` | `cypress/default`          | orb executor |
| `run-ct-tests-in-firefox`            | `cypress/browsers:22.17.0` | docker image |
| …
=> test: migrate Chrome and Firefox tests to orb executor

CONTRIBUTING.md
The [CONTRIBUTING > Commits](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#commits) document section links to an unmaintained repo https://github.com/bahmutov/simple-commit-message (last release in 2021) which is not the definitive reference for commit message syntax used in CircleCI Orbs. It contains the following text, describing a non-standard usage of commit types `major` and `minor`, which is also not typical in other Cypress repos:
---
Use [simple semantic commit convention](https://github.com/bahmutov/simple-commit-message), just prefix your commits. For example:
```text
major: breaking change
minor: new feature added
fix: a patch release
```
---
The associated npm package [simple-commit-message](https://www.npmjs.com/package/simple-commit-message) is not …
=> docs: update contributing conventional commit message advice

.circleci/test-deploy.yml
- The job `Verify resource_class config works` in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) executes the step "Checkout code" twice
- In the job `Verify resource_class config works` in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) job, remove the parameter:
```yml
pre-steps:
- checkout
```
View the log of the "Verify resource_class config works" job and confirm that "Checkout code" only appears once, not twice.
=> test: remove duplicate checkout in Verify resource_class config works

.circleci/test-deploy.yml
- The job `Verify resource_class config works` in [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) runs component testing of [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) and specifies `resource_class: small`
- Cypress documentation [System requirements](https://docs.cypress.io/app/get-started/install-cypress#System-requirements) specifies:
- [CPU](https://docs.cypress.io/app/get-started/install-cypress#CPU) minimum 2 CPUs, plus additional CPUs for app servers
- [Memory](https://docs.cypress.io/app/get-started/install-cypress#Memory) 4GB minimum, 8GB+ for longer test runs
- CircleCI [Docker execution environment](https://circleci.com/docs/configuration-reference/#docker-execut …
=> test: update Verify resource_class config works to medium+

examples/custom-install/package-lock.json, examples/custom-install/package.json, examples/npm-install/package-lock.json, examples/npm-install/package.json, examples/pnpm-install/package.json, examples/pnpm-install/pnpm-lock.yaml, examples/pnpm-install/pnpm-workspace.yaml, examples/wait-on/package-lock.json, examples/wait-on/package.json, examples/yarn-install/package.json, examples/yarn-install/yarn.lock
Example projects that run in CI currently are set up for Cypress `14.x`.
[Cypress 15.0.0](https://docs.cypress.io/app/references/changelog#15-0-0) was released on Aug 20, 2025 and the Orb should demonstrate its ability to run using this version.
Update each of the example projects to use [Cypress 15.0.0](https://docs.cypress.io/app/references/changelog#15-0-0)
- npm `package-lock.json` files are refreshed to `"lockfileVersion": 3`
- [examples/custom-install](https://github.com/cypress-io/circleci-orb/tree/master/examples/custom-install)
- [examples/npm-install](https://github.com/cypress-io/circleci-orb/tree/master/examples/npm-install)
- [examples/pnpm-install](https://github.com/cypress-io/circleci-orb/tree/master/examples/pnpm-install)
pnpm is configured according to …
=> test(deps): update examples to cypress 15.0.0
